### ISSUE TITLE
Website link in the sidebar does not work

### ISSUE THREAD

**Issue by mipals** [SINTEF-COMG/MRST#1]
Hey there,

The link in the sidebar does not seem to work for me. It links to [https://www.mrst.no/](https://www.mrst.no/) but does so using ``https`` which does not redirect. However manually moving from ``https`` to ``http`` the website redirects correctly to [https://www.sintef.no/projectweb/mrst/download/](https://www.sintef.no/projectweb/mrst/download/)

Cheers,
Mikkel

**Comment by moyner** [comment]
Thanks for reporting this! I'll see if our IT admin can't fix https working for the redirect. In the mean time, we have updated the link to `http`.
